## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score


In [16]:
# 讀取鳶尾花資料集
iris = datasets.load_iris()
iris.data.shape

(150, 4)

In [22]:
# 讀取鳶尾花資料集
iris = datasets.load_iris()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.1, random_state=4)



In [24]:
# 建立模型
reg = linear_model.Ridge(alpha=0.5)

# 訓練模型
reg.fit(x_train, y_train)

# 預測測試集
y_pred = reg.predict(x_test)

print(reg.coef_)
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-0.14094001 -0.02886033  0.2580723   0.56913766]
Mean squared error: 0.07


In [25]:
# 建立模型
reg = linear_model.Ridge(alpha=1.0)

# 訓練模型
reg.fit(x_train, y_train)

# 預測測試集
y_pred = reg.predict(x_test)

print(reg.coef_)
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-0.13871647 -0.02630141  0.27140413  0.53510309]
Mean squared error: 0.07


In [26]:
# 建立模型
reg = linear_model.Ridge(alpha=2.0)

# 訓練模型
reg.fit(x_train, y_train)

# 預測測試集
y_pred = reg.predict(x_test)

print(reg.coef_)
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-0.13127417 -0.02481437  0.28955789  0.48330316]
Mean squared error: 0.07
